export const nodePythonInstallLogs = [
    "yarn install",
    "yarn WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142",
    "yarn WARN deprecated har-validator@5.1.5: this library is no longer supported",
    "added 945 packages, and audited 946 packages in 9s",
    "yarn WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):",
    "yarn WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {\"os\":\"darwin\",\"arch\":\"any\"} (current: {\"os\":\"linux\",\"arch\":\"x64\"})",
    "found 0 vulnerabilities",
    "",
    "yarn install express body-parser mongoose",
    "added 50 packages, and audited 996 packages in 5s",
    "found 0 vulnerabilities",
    "",
    "pip install requests flask numpy",
    "Collecting requests",
    "  Downloading requests-2.26.0-py2.py3-none-any.whl (62 kB)",
    "Collecting flask",
    "  Downloading Flask-2.0.2-py3-none-any.whl (95 kB)",
    "Collecting numpy",
    "  Downloading numpy-1.21.2-cp39-cp39-manylinux2010_x86_64.whl (15.9 MB)",
    "Collecting Werkzeug>=2.0",
    "  Downloading Werkzeug-2.0.2-py3-none-any.whl (288 kB)",
    "Collecting Jinja2>=3.0",
    "  Downloading Jinja2-3.0.2-py3-none-any.whl (133 kB)",
    "Collecting itsdangerous>=2.0",
    "  Downloading itsdangerous-2.0.1-py3-none-any.whl (18 kB)",
    "Collecting click>=7.1.2",
    "  Downloading click-8.0.3-py3-none-any.whl (97 kB)",
    "Collecting MarkupSafe>=2.0",
    "  Downloading MarkupSafe-2.0.1-cp39-cp39-manylinux2010_x86_64.whl (27 kB)",
    "Installing collected packages: Werkzeug, MarkupSafe, Jinja2, itsdangerous, click, flask, requests, numpy",
    "Successfully installed Jinja2-3.0.2 MarkupSafe-2.0.1 Werkzeug-2.0.2 click-8.0.3 flask-2.0.2 itsdangerous-2.0.1 numpy-1.21.2 requests-2.26.0",
    ""
];


export const terraformInstallLogs = [
    "Downloading terraform_1.3.5_linux_amd64.zip",
    "Downloading terragrunt_0.35.10_linux_amd64.zip",
    "Installing terraform",
    "Archive:  terraform_1.3.5_linux_amd64.zip",
    "inflating: terraform",
    "Terraform v1.3.5 installed successfully",
    "",
    "Installing terragrunt",
    "Archive:  terragrunt_0.35.10_linux_amd64.zip",
    "inflating: terragrunt",
    "Terragrunt v0.35.10 installed successfully",
    "",
    "terraform --version",
    "Terraform v1.3.5",
    "on linux_amd64",
    "",
    "terragrunt --version",
    "terragrunt version v0.35.10",
    ""
];

export const awsCliInstallLogs = [
    "Downloading awscli-exe-linux-x86_64.zip",
    "Unzipping awscli-exe-linux-x86_64.zip",
    "aws-cli/",
    "aws-cli/v2/",
    "aws-cli/v2/current/",
    "aws-cli/v2/current/dist/",
    "aws-cli/v2/current/dist/aws/",
    "aws-cli/v2/current/dist/aws/cli/",
    "aws-cli/v2/current/dist/aws/cli/command/",
    "aws-cli/v2/current/dist/awscli/",
    "aws-cli/v2/current/dist/awscli/__main__.py",
    "...",
    "Installing AWS CLI v2",
    "You can now run: /usr/local/bin/aws --version",
    "AWS CLI v2 installed successfully",
    "",
    "aws --version",
    "aws-cli/2.4.11 Python/3.8.8 Linux/4.14.219-161.340.amzn2.x86_64 exe/x86_64.amzn.2 prompt/off",
    "",
    "Downloading https://github.com/Versent/saml2aws/releases/download/v2.29.0/saml2aws_2.29.0_linux_amd64.tar.gz",
    "Extracting saml2aws_2.29.0_linux_amd64.tar.gz",
    "saml2aws",
    "Moving saml2aws to /usr/local/bin/",
    "saml2aws v2.29.0 installed successfully",
    "",
    "saml2aws --version",
    "saml2aws 2.29.0",
    ""
];

export const gitInstallLogs = [
    "Downloading git-2.33.0.tar.gz",
    "Extracting git-2.33.0.tar.gz",
    "Compiling Git source code",
    "checking for gcc... gcc",
    "checking whether the C compiler works... yes",
    "...",
    "Installing Git",
    "Git v2.33.0 installed successfully",
    "",
    "git --version",
    "git version 2.33.0",
    "",
    "Downloading GitHubDesktop-linux-2.9.0-linux1.deb",
    "Installing GitHub Desktop",
    "Selecting previously unselected package github-desktop.",
    "(Reading database ... 250000 files and directories currently installed.)",
    "Preparing to unpack GitHubDesktop-linux-2.9.0-linux1.deb ...",
    "Unpacking github-desktop (2.9.0-linux1) ...",
    "Setting up github-desktop (2.9.0-linux1) ...",
    "GitHub Desktop v2.9.0 installed successfully",
    "",
    "github-desktop --version",
    "github-desktop 2.9.0",
    ""
];